global:
  namespace: crypto-trackers

kafka:
  replicas: 1
  image: confluentinc/cp-kafka:7.4.0
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
  storage:
    size: 1Gi
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"

dataIngestion:
  replicaCount: 1
  image:
    repository: crypto-trackers/data-ingestion
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  pollingInterval: 60
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

maSignalDetector:
  replicaCount: 1
  image:
    repository: crypto-trackers/ma-signal-detector
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  kafkaGroupId: "ma-signal-detector"
  logLevel: "INFO"
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

config:
  kafka:
    bootstrapServers: "kafka-service:9092"
    topics:
      cryptoPrices: "crypto-prices"
      tradingSignals: "trading-signals"
  api:
    pollingInterval: 60
    coingecko:
      baseUrl: "https://api.coingecko.com/api/v3"