apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crypto-trackers.fullname" . }}-data-ingestion
  labels:
    {{- include "crypto-trackers.labels" . | nindent 4 }}
    app.kubernetes.io/component: data-ingestion
spec:
  replicas: {{ .Values.dataIngestion.replicaCount }}
  selector:
    matchLabels:
      {{- include "crypto-trackers.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: data-ingestion
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "crypto-trackers.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: data-ingestion
    spec:
      containers:
      - name: data-ingestion
        image: "{{ .Values.dataIngestion.image.repository }}:{{ .Values.dataIngestion.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.dataIngestion.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: {{ include "crypto-trackers.fullname" . }}-kafka:9092
        - name: POLLING_INTERVAL
          value: "{{ .Values.dataIngestion.pollingInterval }}"
        - name: PORT
          value: "8080"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          {{- toYaml .Values.dataIngestion.resources | nindent 12 }}