apiVersion: v1
kind: Service
metadata:
  name: {{ include "crypto-trackers.fullname" . }}-data-ingestion
  labels:
    {{- include "crypto-trackers.labels" . | nindent 4 }}
    app.kubernetes.io/component: data-ingestion
spec:
  type: {{ .Values.dataIngestion.service.type }}
  ports:
    - port: {{ .Values.dataIngestion.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "crypto-trackers.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: data-ingestion
