apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "crypto-signals.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "crypto-signals.labels" . | nindent 4 }}
    app.kubernetes.io/component: configuration
  annotations:
    description: "Global configuration for crypto trading signal detection services"
data:
  # Kafka configuration
  kafka-bootstrap-servers: {{ .Values.config.kafkaBootstrapServers | quote }}
  kafka-topic-prefix: {{ .Values.config.kafkaTopicPrefix | quote }}
  kafka-topic-prices: "crypto-prices"
  kafka-topic-signals: "trading-signals"
  
  # Logging configuration
  log-level: {{ .Values.config.logLevel | quote }}
  log-format: {{ .Values.config.logFormat | quote }}
  
  # Service discovery
  service-discovery-namespace: {{ .Values.config.serviceDiscoveryNamespace | quote }}
  
  # API configuration
  api-timeout: {{ .Values.config.apiTimeout | quote }}
  api-retry-attempts: {{ .Values.config.apiRetryAttempts | quote }}