apiVersion: v1
kind: Service
metadata:
  name: {{ include "crypto-signals.fullname" . }}-kafka-headless
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "crypto-signals.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
spec:
  clusterIP: None
  ports:
  - port: 9092
    targetPort: kafka
    protocol: TCP
    name: kafka
  - port: 9093
    targetPort: kafka-internal
    protocol: TCP
    name: kafka-internal
  selector:
    {{- include "crypto-signals.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "crypto-signals.fullname" . }}-kafka
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "crypto-signals.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
spec:
  ports:
  - port: 9092
    targetPort: kafka
    protocol: TCP
    name: kafka
  selector:
    {{- include "crypto-signals.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kafka