apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "crypto-signals.fullname" . }}-zookeeper
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "crypto-signals.labels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
spec:
  serviceName: {{ include "crypto-signals.fullname" . }}-zookeeper-headless
  replicas: {{ .Values.zookeeper.replicas }}
  selector:
    matchLabels:
      {{- include "crypto-signals.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: zookeeper
  template:
    metadata:
      labels:
        {{- include "crypto-signals.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: "{{ .Values.zookeeper.image.repository }}:{{ .Values.zookeeper.image.tag }}"
        imagePullPolicy: {{ .Values.zookeeper.image.pullPolicy }}
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        env:
        - name: ZOOKEEPER_SERVER_ID
          value: "$(echo ${HOSTNAME} | sed 's/.*-//' | awk '{print $1+1}')"
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        - name: ZOOKEEPER_INIT_LIMIT
          value: "5"
        - name: ZOOKEEPER_SYNC_LIMIT
          value: "2"
        - name: ZOOKEEPER_SERVERS
          value: "{{ include "crypto-signals.fullname" . }}-zookeeper-0.{{ include "crypto-signals.fullname" . }}-zookeeper-headless.{{ .Values.namespace }}.svc.cluster.local:2888:3888;{{ include "crypto-signals.fullname" . }}-zookeeper-1.{{ include "crypto-signals.fullname" . }}-zookeeper-headless.{{ .Values.namespace }}.svc.cluster.local:2888:3888;{{ include "crypto-signals.fullname" . }}-zookeeper-2.{{ include "crypto-signals.fullname" . }}-zookeeper-headless.{{ .Values.namespace }}.svc.cluster.local:2888:3888"
        resources:
          {{- toYaml .Values.zookeeper.resources | nindent 10 }}
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/zookeeper/data
        - name: datalogdir
          mountPath: /var/lib/zookeeper/log
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "echo ruok | nc localhost 2181 | grep imok"
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "echo ruok | nc localhost 2181 | grep imok"
          initialDelaySeconds: 5
          periodSeconds: 10
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                  - zookeeper
              topologyKey: kubernetes.io/hostname
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.zookeeper.storage.storageClass }}
      storageClassName: {{ .Values.zookeeper.storage.storageClass }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.zookeeper.storage.size }}
  - metadata:
      name: datalogdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.zookeeper.storage.storageClass }}
      storageClassName: {{ .Values.zookeeper.storage.storageClass }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.zookeeper.storage.size }}