apiVersion: v1
kind: Service
metadata:
  name: {{ include "crypto-signals.fullname" . }}-zookeeper-headless
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "crypto-signals.labels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
spec:
  clusterIP: None
  ports:
  - port: 2181
    targetPort: client
    protocol: TCP
    name: client
  - port: 2888
    targetPort: server
    protocol: TCP
    name: server
  - port: 3888
    targetPort: leader-election
    protocol: TCP
    name: leader-election
  selector:
    {{- include "crypto-signals.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "crypto-signals.fullname" . }}-zookeeper
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "crypto-signals.labels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
spec:
  ports:
  - port: 2181
    targetPort: client
    protocol: TCP
    name: client
  selector:
    {{- include "crypto-signals.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper