apiVersion: v1
kind: Service
metadata:
  name: {{ include "crypto-trackers.fullname" . }}-volume-spike-detector
  labels:
    {{- include "crypto-trackers.labels" . | nindent 4 }}
    app.kubernetes.io/component: volume-spike-detector
spec:
  type: {{ .Values.volumeSpikeDetector.service.type }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "crypto-trackers.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: volume-spike-detector
