apiVersion: v1
kind: Service
metadata:
  name: zookeeper-headless
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "crypto-signals.labels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
spec:
  clusterIP: None
  ports:
  - port: 2181
    name: client
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  selector:
    {{- include "crypto-signals.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "crypto-signals.labels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
spec:
  ports:
  - port: 2181
    name: client
  selector:
    {{- include "crypto-signals.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper