apiVersion: v1
kind: Service
metadata:
  name: {{ include "crypto-trackers.fullname" . }}-ma-signal-detector
  labels:
    {{- include "crypto-trackers.labels" . | nindent 4 }}
    app.kubernetes.io/component: ma-signal-detector
spec:
  type: {{ .Values.maSignalDetector.service.type }}
  ports:
    - port: {{ .Values.maSignalDetector.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "crypto-trackers.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ma-signal-detector